### ISSUE TITLE
警告提示

### ISSUE THREAD

**Issue by GuoRan18** [zsdycs/lipk.org#11]
你好，在用了主题以后执行hugo后提示`Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url`

**Comment by zsdycs** [comment]
这是一个 **WARN**。

警告来自 `hearder.html` 和 `menu.html`。

感谢反馈。

**Comment by zsdycs** [comment]
[修改](https://github.com/zsdycs/lipk.org/commit/0b25ca80ad2259f30da41e0c679bbdbde4dad390) 已经提交。
